// list of languages to be used by the landing page as a list of available languages, will change eventually

export const Language = [
    {language: "General", emoji: '🌎', code: 'gen'},
    {language: "Mandarin Chinese", emoji: '🇨🇳', code: 'zh'},
    {language: "Spanish", emoji: '🇪🇸', code: 'es'},
    {language: "English", emoji: '🇬🇧', code: 'en'},
    {language: "Hindi", emoji: '🇮🇳', code: 'hi'},
    {language: "Arabic", emoji: '🇸🇦', code: 'ar'},
    {language: "Bengali", emoji: '🇧🇩', code: 'bn'},
    {language: "Portuguese", emoji: '🇵🇹', code: 'pt'},
    {language: "Russian", emoji: '🇷🇺', code: 'ru'},
    {language: "Japanese", emoji: '🇯🇵', code: 'ja'},
    {language: "Punjabi", emoji: '🇮🇳', code: 'pa'},
    {language: "German", emoji: '🇩🇪', code: 'de'},
    {language: "Javanese", emoji: '🇮🇩', code: 'jv'},
    {language: "Wu Chinese", emoji: '🇨🇳', code: 'wuu'},
    {language: "Malay", emoji: '🇲🇾', code: 'ms'},
    {language: "Telugu", emoji: '🇮🇳', code: 'te'},
    {language: "Vietnamese", emoji: '🇻🇳', code: 'vi'},
    {language: "Korean", emoji: '🇰🇷', code: 'ko'},
    {language: "French", emoji: '🇫🇷', code: 'fr'},
    {language: "Marathi", emoji: '🇮🇳', code: 'mr'},
    {language: "Tamil", emoji: '🇮🇳', code: 'ta'},
    {language: "Urdu", emoji: '🇵🇰', code: 'ur'},
    {language: "Persian", emoji: '🇮🇷', code: 'fa'},
    {language: "Turkish", emoji: '🇹🇷', code: 'tr'},
    {language: "Italian", emoji: '🇮🇹', code: 'it'},
    {language: "Yue Chinese", emoji: '🇭🇰', code: 'yue'},
    {language: "Thai", emoji: '🇹🇭', code: 'th'},
    {language: "Gujarati", emoji: '🇮🇳', code: 'gu'},
    {language: "Jin Chinese", emoji: '🇨🇳', code: 'jinyu'},
    {language: "Southern Min", emoji: '🇹🇼', code: 'nan'},
    {language: "Polish", emoji: '🇵🇱', code: 'pl'},
    {language: "Pashto", emoji: '🇦🇫', code: 'ps'}
]